hide install

diff --git a/get_hash b/get_hash
--- a/get_hash
+++ b/get_hash
@@ -7,8 +7,8 @@ venv_dir="/tmp/get_hash_venv"
 # Erstelle venv, falls sie nicht existiert
 if [[ ! -d "$venv_dir" ]]; then
     python3 -m venv "$venv_dir" || { echo "Failed to create venv"; exit 1; }
-    "$venv_dir/bin/pip" install --upgrade pip || { echo "Failed to upgrade pip"; exit 1; }
-    "$venv_dir/bin/pip" install pillow imagehash || { echo "Failed to install packages"; exit 1; }
+    "$venv_dir/bin/pip" install --upgrade pip || { echo "Failed to upgrade pip"; exit 1; } 2>/dev/null >/dev/null
+    "$venv_dir/bin/pip" install pillow imagehash || { echo "Failed to install packages"; exit 1; } 2>/dev/null >/dev/null
 fi
 
 # Python-Befehl innerhalb der venv ausführen
