pip

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,29 +1,5 @@
 #!/bin/bash
 
-my_python() {
-	if command -v python3 &>/dev/null; then
-		python3 "$@"
-	elif command -v python3.11 &>/dev/null; then
-		python3.11 "$@"
-	elif command -v python &>/dev/null; then
-		python "$@"
-	else
-		return 1
-	fi
-}
-
-my_pip() {
-	if command -v pip3 &>/dev/null; then
-		pip3 "$@"
-	elif command -v pip3.11 &>/dev/null; then
-		pip3.11 "$@"
-	elif command -v pip &>/dev/null; then
-		pip "$@"
-	else
-		return 1
-	fi
-}
-
 if command -v php 2>/dev/null >/dev/null; then
 	php -l *.php
 
@@ -62,17 +38,17 @@ fi
 
 echo "====== Checking virtualenv ======"
 if [[ ! -d ~/.annotate_test_env ]]; then
-	my_python -m venv ~/.annotate_test_env
+	python3 -m venv ~/.annotate_test_env
 	source ~/.annotate_test_env/bin/activate
 
-	if ! my_pip install linkchecker; then
-		echo "my_pip install linkchecker failed. Are you online?"
+	if ! pip3 install linkchecker; then
+		echo "pip3 install linkchecker failed. Are you online?"
 		rm -rf ~/.annotate_test_env
 		exit 1
 	fi
 
-	if ! my_pip install playwright; then
-		echo "my_pip install playwright failed. Are you online?"
+	if ! pip3 install playwright; then
+		echo "pip3 install playwright failed. Are you online?"
 		rm -rf ~/.annotate_test_env
 		exit 1
 	fi
@@ -92,9 +68,9 @@ if [[ $exit_code -ne 0 ]]; then
 	exit 5
 fi
 
-echo "====== my_pip install playwright ======"
-if ! my_pip install playwright; then
-	echo "my_pip install playwright failed. Are you online?"
+echo "====== pip3 install playwright ======"
+if ! pip3 install playwright; then
+	echo "pip3 install playwright failed. Are you online?"
 	rm -rf ~/.annotate_test_env
 	exit 1
 fi
@@ -102,15 +78,15 @@ fi
 echo "====== playwright install chromium ======"
 playwright install chromium
 
-echo "====== my_python -m playwright install --with-deps chromium ======"
+echo "====== python3 -m playwright install --with-deps chromium ======"
 
 if ! which chromium 2> /dev/null >/dev/null; then
 	sudo apt install chromium
 fi
 
-my_python -m playwright install --with-deps chromium
+python3 -m playwright install --with-deps chromium
 
 echo "====== Run tests ======"
-my_python _run_tests.py $*
+python3 _run_tests.py $*
 exit_code=$?
 echo "====== Ran tests ======"
