test upload model

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -29,12 +29,12 @@ if [[ $exit_code -ne 0 ]]; then
 	exit $exit_code
 fi
 
-#bash tests/upload_model -h localhost
-#exit_code=$?
-#if [[ $exit_code -ne 0 ]]; then
-#	echo "bash tests/upload_model failed with exit_code $exit_code"
-#	exit 1
-#fi
+bash tests/upload_model -h localhost
+exit_code=$?
+if [[ $exit_code -ne 0 ]]; then
+	echo "bash tests/upload_model failed with exit_code $exit_code"
+	exit 1
+fi
 
 echo "====== Checking virtualenv ======"
 if [[ ! -d ~/.annotate_test_env ]]; then
