fix

diff --git a/test_convert_to_tfjs b/test_convert_to_tfjs
--- a/test_convert_to_tfjs
+++ b/test_convert_to_tfjs
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [[ ! -e tests/last.pt ]]; then
+	echo "tests/last.pt not found"
+	exit 1
+fi
+
 bash convert_to_tfjs tests/last.pt /tmp/UFO_TEST
 
 if [[ $exit_code != 0 ]]; then
@@ -9,7 +14,7 @@ fi
 
 if [[ ! -d /tmp/UFO_TEST/last_web_model ]]; then
 	echo "/tmp/UFO_TEST/last_web_model not found"
-	exit 1
+	exit 2
 fi
 
 exit 0
