tests in smaller units

diff --git a/tests/empty_page b/tests/empty_page
--- a/tests/empty_page
+++ b/tests/empty_page
@@ -1,13 +1,8 @@
 #!/bin/bash
 
-page=$(curl -sS http://localhost:9912/)
-
-nr_no_res_str=$(echo $page | grep "No images are available" | wc -l)
-
-if [[ $nr_no_res_str -ne 1 ]]; then
-	echo "!!! page does not contain 'No images are available' exactly in one line !!!"
-	echo "$page"
+bash tests/empty_page
+exit_code=$?
+if [[ $exit_code -ne 0 ]]; then
+	echo "bash tests/empty_page failed with exit_code $exit_code"
 	exit 1
 fi
-
-exit 0
