fix

diff --git a/tests/export_and_train b/tests/export_and_train
--- a/tests/export_and_train
+++ b/tests/export_and_train
@@ -25,4 +25,7 @@ for needs_to_exists in dataset.yaml labels labels.json train visualize; do
 	fi
 done
 
+bash -n train || { echo "Failed: train is not a valid bash file"; exit 4 }
+bash -n visualize || { echo "Failed: visualize is not a valid bash file"; exit 5 }
+
 exit 0
